language: generic
sudo: required
dist: trusty
services:
- docker
env:
  global:
    secure: SEmoQX+UamjeygKxVTNfu6/KIIDnAIhKZAvj97dIL5YWUjg5TtWyQoFfs1rWoMwKknguACdnFurFWvAVCfk5wLmiyvG6EdsBJjjWsfYm3z/O/w+cyYTBFH+aKHRlYCNk0Ziwgd4hJrZcPHO7zTd8PP8dBMWujZd980/7vI16ll3NQx2HE74Gg3qCTWatr59qcQOD0D8ZMMvtzhFyuUTHFDp7pwM3lT2qc5TgfPQzvDz4ky8O5qRST0oZnngxB7Z+qVc059ibPGExJmMhx/BcpSMT+YDqqwhB6wuaKRdsUWTlQD9pjSNOhdXdeCA+kD2e5B91weau3WOUNKnVxXdql8NLy1LHrD8j7tMzQ2tDVntoQjGtdLpd2/D76g9Csu16xr7cJKs6sIUtcRA8x7HVJqRhahjEaB7K2Z5hWEd9x1JaoShtIZhaBRxuZkng/lcQRsTkDnPlhRnFgECwkUGd127XyzmEJF6fkLTZ1jyP7Fia1RPemJvHg7cc+a/XPnjk/eBdg9wEBLip1WTE+499cS59Fx04BAXG2RPHyls7iWgeKT9HTVoEvLt4hVLIf7vCIlas+aDN0VI0QfRDGGYkr2w4o0UqV8ijonzxKBTt5DyMEm1qv1sGx9LNzfDNWwrtGxMO0y1tyLHIq0kxGZgzFsfw3nmt/bjHcqW6Siwf66E=
install:
- git reset --hard
script:
- make bazel-generate
- if [[ -n "$(git status --porcelain)" ]] ; then echo "It seems like you need to run
  `make bazel-generate`. Please run it and commit the changes"; git status --porcelain;
  false; fi
- CONTAINER_TAG=$TRAVIS_TAG make bazel-generate-manifests-release
- echo "${TEST}"
- hack/dockerized "docker login -u=${DOCKER_USER} -p=${DOCKER_PASSWORD}"
deploy:
- provider: script
  script: hack/dockerized "docker login -u=${DOCKER_USER} -p=${DOCKER_PASSWORD}" &&
    CONTAINER_TAG=latest make bazel-push-images-release
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: hack/dockerized "docker login -u=\"$DOCKER_USER\" -p=\"$DOCKER_PASSWORD\""
    && CONTAINER_TAG=$TRAVIS_TAG make bazel-push-images-release
  skip_cleanup: true
  on:
    tags: true
- provider: releases
  skip_cleanup: true
  api_key:
    secure: HfTOaydOlOoZJH6zrRkaBoMRRi6T/qQ48LZOvgYOVVxrY65RJxcJGPIWuSHmTaG4gVnbvZX10X45hb3wdjNHQVAT/fJ4K5+7FFShdSF25bXgYgATJPvXwd4P9efq+4SL9z22NsEDc0vB3f354e5OMcT3USmV9Mp/u5wBporar01JEOeyb9P+PUYJkSZvlOIu3VI0FKEFIxjtaJjBEsbHNJAly+Ccdlpja/vViNxOB6jcq6EvhQZI95BnqSnTt89wG4veRr5L1EGse76FujA69RXvbXnZ3Aq8OdiIMtxXqg4N+jkQWtT2M6SkH6MbKTqW9mRfSIRmYFLhZH+PC429PpHxKGHc/JoVR61H8gy8IxAybNLQtRLIVPZ9pZNrOiLJXDr6TInyWGbYOnGev1FYslSEqllDKzF04b+lBpuzBzfvDj9yzoDo1dqZSAh4SnXtLWx+ML9zldPGEqoDltRdBXEmd72Zn46fApXfQ0N2knHMQPGBJ0kuQTwLl2fjkkV2SwIZrxMaQa/3FrNykkz0iwMwA7MsZmhNMqbMO/IkFUqylWZctfodjPfXuviUfe3Ff5jjbsu7BFexYOVmgLP8fibLpXxGGqwe8Qe748UPhslgPgkqLvPtlTcAa9i1PFPlybEBHY19+STElkl60Qkzo5ftd3rRs66x+oiUOkZCM2Q=
  file: _out/manifests/cluster-api-provider-external.yaml
  prerelease: true
  overwrite: true
  name: "$TRAVIS_TAG"
  on:
    repo: kubevirt/cluster-api-provider-external
    tags: true
notifications:
  irc:
    channels:
    - chat.freenode.net#kubevirt
    on_success: change
    on_failure: always
