---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Cluster
metadata:
  name: example-cluster
  namespace: cluster-api-provider-baremetal
  labels:
    cluster-api-provider-baremetal.kubevirt.io: ""
spec:
    providerSpec:
      value:
        apiVersion: "baremetalproviderconfig.kubevirt.io/v1alpha1"
        kind: "BareMetalClusterProviderSpec"
