---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: example-machine
  namespace: cluster-api-provider-baremetal
  labels:
    cluster-api-provider-baremetal.kubevirt.io: ""
spec:
  providerSpec:
    value:
      apiVersion: "baremetalproviderconfig.kubevirt.io/v1alpha1"
      kind: "BareMetalMachineProviderSpec"
      nodeName: node02
      fencingConfig:
        agentType: "ipmilan"
        agentAddress: "had-15-drac.ha.lab.eng.bos.redhat.com"
        agentSecret:
          data:
            username: cm9vdAo=
            password: Y2FsdmluCg==
