##############################################################################
## Discover a machine's power status with IPMI
##############################################################################

- name: Determin machine power state
  command: "/sbin/fence_{{ agent_type }} --username {{ agent_username }} --password {{ agent_password }} --ip {{ agent_address }} {{ options }} -o status"
