##############################################################################
## Power on an machine with IPMI
##############################################################################

- name: Power on machine
  command: "/sbin/fence_{{ agent_type }} --username {{ agent_username }} --password {{ agent_password }} --ip {{ agent_address }} {{ agent_options }} -o on"