##############################################################################
## Power off an machine with IPMI
##############################################################################

- name: Power off machine
  command: "/sbin/fence_{{ agent_type }} --username {{ agent_username }} --password {{ agent_password }} --ip {{ agent_address }} {{ agent_options }} -o off"
